
-- MySQL Script generated by MySQL Workbench
-- Fri Jun 24 11:03:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TrabalhoDelphi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TrabalhoDelphi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TrabalhoDelphi` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema TrabalhoDelphi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TrabalhoDelphi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TrabalhoDelphi` DEFAULT CHARACTER SET utf8mb3 ;
-- -----------------------------------------------------
-- Schema TrabalhoDelphi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TrabalhoDelphi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TrabalhoDelphi` DEFAULT CHARACTER SET utf8mb3 ;
USE `TrabalhoDelphi` ;

-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`Crientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`Crientes` (
  `idCriente` INT NOT NULL AUTO_INCREMENT,
  `ClienteNome` VARCHAR(60) NOT NULL,
  `ClienteSobreNome` VARCHAR(60) NOT NULL,
  `ClienteCpf` VARCHAR(11) NOT NULL,
  `ClienteTelefone` VARCHAR(11) NOT NULL,
  `ClienteEmail` VARCHAR(60) NOT NULL,
  `ClienteRua` VARCHAR(60) NOT NULL,
  `ClienteNumero` VARCHAR(60) NOT NULL,
  `ClienteBairro` VARCHAR(60) NOT NULL,
  `ClienteCidade` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idCriente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`Produtos` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `ProdutoNome` VARCHAR(60) NOT NULL,
  `ProdutoPreco` DECIMAL(7,2) NOT NULL,
  `ProdutoDescricao` TEXT(255) NOT NULL,
  `ProdutoImagem` BLOB NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`Pedidos` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `PedidoFrete` DECIMAL(7,2) NOT NULL,
  `PedidoPrecoTotal` DECIMAL(7,2) NOT NULL,
  `PedidoPrecoTotalProduto` DECIMAL(7,2) NOT NULL,
  `PedidoData` DATE NOT NULL,
  `Clientes_idCliente` INT NOT NULL,
  `Vendedores_idVendedor` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedidos_Clientes1_idx` (`Clientes_idCliente` ASC),
  INDEX `fk_Pedidos_Vendedores1_idx` (`Vendedores_idVendedor` ASC),
  CONSTRAINT `fk_Pedidos_Clientes1`
    FOREIGN KEY (`Clientes_idCliente`)
    REFERENCES `mydb`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Vendedores1`
    FOREIGN KEY (`Vendedores_idVendedor`)
    REFERENCES `mydb`.`Vendedores` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`Vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`Vendedores` (
  `idVendedor` INT NOT NULL AUTO_INCREMENT,
  `VendedorNome` VARCHAR(60) NOT NULL,
  `VendedorSobrenome` VARCHAR(60) NOT NULL,
  `VendedorTelefone` VARCHAR(11) NOT NULL,
  `VendedorEmail` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idVendedor`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`PedidosProdutos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`PedidosProdutos` (
  `Pedidos_idPedido` INT NOT NULL,
  `Produtos_idProduto` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  `PrecoUnitario` DECIMAL(7,2) NOT NULL,
  `PrecoTotal` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`Pedidos_idPedido`, `Produtos_idProduto`),
  INDEX `fk_Pedidos_has_Produtos_Produtos1_idx` (`Produtos_idProduto` ASC),
  INDEX `fk_Pedidos_has_Produtos_Pedidos_idx` (`Pedidos_idPedido` ASC),
  CONSTRAINT `fk_Pedidos_has_Produtos_Pedidos`
    FOREIGN KEY (`Pedidos_idPedido`)
    REFERENCES `TrabalhoDelphi`.`Pedidos` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_has_Produtos_Produtos1`
    FOREIGN KEY (`Produtos_idProduto`)
    REFERENCES `TrabalhoDelphi`.`Produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `TrabalhoDelphi` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;