-- MySQL Script generated by MySQL Workbench
-- Fri Jun 24 11:03:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TrabalhoDelphi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TrabalhoDelphi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TrabalhoDelphi` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema TrabalhoDelphi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TrabalhoDelphi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TrabalhoDelphi` DEFAULT CHARACTER SET utf8mb3 ;
-- -----------------------------------------------------
-- Schema TrabalhoDelphi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TrabalhoDelphi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TrabalhoDelphi` DEFAULT CHARACTER SET utf8mb3 ;
USE `TrabalhoDelphi` ;

-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`Crientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`Crientes` (
  `idCriente` INT NOT NULL AUTO_INCREMENT,
  `ClienteNome` VARCHAR(60) NOT NULL,
  `ClienteSobreNome` VARCHAR(60) NOT NULL,
  `ClienteCpf` VARCHAR(11) NOT NULL,
  `ClienteTelefone` VARCHAR(11) NOT NULL,
  `ClienteEmail` VARCHAR(60) NOT NULL,
  `ClienteRua` VARCHAR(60) NOT NULL,
  `ClienteNumero` VARCHAR(60) NOT NULL,
  `ClienteBairro` VARCHAR(60) NOT NULL,
  `ClienteCidade` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idCriente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`Produtos` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `ProdutoNome` VARCHAR(60) NOT NULL,
  `ProdutoPreco` DECIMAL(7,2) NOT NULL,
  `ProdutoDescricao` TEXT(255) NOT NULL,
  `ProdutoImagem` BLOB NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`Pedidos` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `PedidoFrete` DECIMAL(7,2) NOT NULL,
  `PedidoPrecoTotal` DECIMAL(7,2) NOT NULL,
  `PedidoPrecoTotalProduto` DECIMAL(7,2) NOT NULL,
  `PedidoData` DATE NOT NULL,
  `Clientes_idCliente` INT NOT NULL,
  `Vendedores_idVendedor` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedidos_Clientes1_idx` (`Clientes_idCliente` ASC) VISIBLE,
  INDEX `fk_Pedidos_Vendedores1_idx` (`Vendedores_idVendedor` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_Clientes1`
    FOREIGN KEY (`Clientes_idCliente`)
    REFERENCES `mydb`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Vendedores1`
    FOREIGN KEY (`Vendedores_idVendedor`)
    REFERENCES `mydb`.`Vendedores` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`Vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`Vendedores` (
  `idVendedor` INT NOT NULL AUTO_INCREMENT,
  `VendedorNome` VARCHAR(60) NOT NULL,
  `VendedorSobrenome` VARCHAR(60) NOT NULL,
  `VendedorTelefone` VARCHAR(11) NOT NULL,
  `VendedorEmail` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idVendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`Clientes` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `ClienteNome` VARCHAR(60) NOT NULL,
  `ClienteSobrenome` VARCHAR(60) NOT NULL,
  `ClienteCpf` VARCHAR(11) NOT NULL,
  `ClienteTelefone` VARCHAR(11) NOT NULL,
  `ClienteEmail` VARCHAR(60) NOT NULL,
  `ClienteRua` VARCHAR(60) NOT NULL,
  `ClienteNumero` VARCHAR(60) NOT NULL,
  `ClienteCidade` VARCHAR(60) NOT NULL,
  `ClienteBairro` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`Vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`Vendedores` (
  `idVendedor` INT NOT NULL AUTO_INCREMENT,
  `VendedorNome` VARCHAR(60) NOT NULL,
  `VendedorSobrenome` VARCHAR(60) NOT NULL,
  `VendedorTelefone` VARCHAR(11) NOT NULL,
  `VendedorEmail` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idVendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`Pedidos` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `PedidoFrete` DECIMAL(7,2) NOT NULL,
  `PedidoPrecoTotal` DECIMAL(7,2) NOT NULL,
  `PedidoPrecoTotalProduto` DECIMAL(7,2) NOT NULL,
  `PedidoData` DATE NOT NULL,
  `Clientes_idCliente` INT NOT NULL,
  `Vendedores_idVendedor` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedidos_Clientes1_idx` (`Clientes_idCliente` ASC) VISIBLE,
  INDEX `fk_Pedidos_Vendedores1_idx` (`Vendedores_idVendedor` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_Clientes1`
    FOREIGN KEY (`Clientes_idCliente`)
    REFERENCES `mydb`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Vendedores1`
    FOREIGN KEY (`Vendedores_idVendedor`)
    REFERENCES `mydb`.`Vendedores` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`Produtos` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `ProdutoNome` VARCHAR(60) NOT NULL,
  `ProdutoPreco` DECIMAL(7,2) NOT NULL,
  `ProdutoDescricao` TEXT(255) NOT NULL,
  `ProdutoImagem` BLOB NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`PedidosProdutos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`PedidosProdutos` (
  `Pedidos_idPedido` INT NOT NULL,
  `Produtos_idProduto` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  `PrecoUnitario` DECIMAL(7,2) NOT NULL,
  `PrecoTotal` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`Pedidos_idPedido`, `Produtos_idProduto`),
  INDEX `fk_Pedidos_has_Produtos_Produtos1_idx` (`Produtos_idProduto` ASC) VISIBLE,
  INDEX `fk_Pedidos_has_Produtos_Pedidos_idx` (`Pedidos_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_has_Produtos_Pedidos`
    FOREIGN KEY (`Pedidos_idPedido`)
    REFERENCES `mydb`.`Pedidos` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_has_Produtos_Produtos1`
    FOREIGN KEY (`Produtos_idProduto`)
    REFERENCES `mydb`.`Produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `TrabalhoDelphi` ;

-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`Pedidos` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `PedidoFrete` DECIMAL(7,2) NOT NULL,
  `PedidoPrecoTotal` DECIMAL(7,2) NOT NULL,
  `PedidoPrecoTotalProduto` DECIMAL(7,2) NOT NULL,
  `PedidoData` DATE NOT NULL,
  `Vendedores_idVendedor` INT NOT NULL,
  `Crientes_idCriente` INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_Pedidos_Vendedores1_idx` (`Vendedores_idVendedor` ASC) VISIBLE,
  INDEX `fk_Pedidos_Crientes1_idx` (`Crientes_idCriente` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_Vendedores1`
    FOREIGN KEY (`Vendedores_idVendedor`)
    REFERENCES `mydb`.`Vendedores` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Crientes1`
    FOREIGN KEY (`Crientes_idCriente`)
    REFERENCES `mydb`.`Crientes` (`idCriente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`Produtos` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `ProdutoNome` VARCHAR(100) NOT NULL,
  `ProdutoDescricao` TEXT NOT NULL,
  `ProdutoPreco` DECIMAL(7,2) NOT NULL,
  `ProdutoImagem` BLOB NOT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`Pedidos_Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`Pedidos_Produtos` (
  `Pedidos_idpedido` INT NOT NULL,
  `Produtos_idproduto` INT NOT NULL,
  `Quantidade` FLOAT NULL,
  `Preco_Unitario` FLOAT NULL,
  `Preto_Total` FLOAT NULL,
  PRIMARY KEY (`Pedidos_idpedido`, `Produtos_idproduto`),
  INDEX `fk_Pedidos_has_Produtos_Produtos1_idx` (`Produtos_idproduto` ASC) VISIBLE,
  INDEX `fk_Pedidos_has_Produtos_Pedidos1_idx` (`Pedidos_idpedido` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_has_Produtos_Pedidos1`
    FOREIGN KEY (`Pedidos_idpedido`)
    REFERENCES `trabalho_pratico`.`Pedidos` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_has_Produtos_Produtos1`
    FOREIGN KEY (`Produtos_idproduto`)
    REFERENCES `trabalho_pratico`.`Produtos` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

USE `TrabalhoDelphi` ;

-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `idDadosPessoais` INT NOT NULL,
  `idpedido` INT NOT NULL,
  `idendereco` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_cliente_dadospessoais_idx` (`idDadosPessoais` ASC) VISIBLE,
  INDEX `fk_cliente_pedido1_idx` (`idpedido` ASC) VISIBLE,
  INDEX `fk_cliente_endereco1_idx` (`idendereco` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_dadospessoais`
    FOREIGN KEY (`idDadosPessoais`)
    REFERENCES `trabalho_pratico`.`dadospessoais` (`idDadosPessoais`),
  CONSTRAINT `fk_cliente_endereco1`
    FOREIGN KEY (`idendereco`)
    REFERENCES `trabalho_pratico`.`endereco` (`idendereco`),
  CONSTRAINT `fk_cliente_pedido1`
    FOREIGN KEY (`idpedido`)
    REFERENCES `trabalho_pratico`.`pedido` (`idpedido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`dadospessoais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`dadospessoais` (
  `idDadosPessoais` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `sobrenome` VARCHAR(100) NULL DEFAULT NULL,
  `cpf` VARCHAR(11) NULL DEFAULT NULL,
  `telefone` VARCHAR(11) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idDadosPessoais`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(100) NULL DEFAULT NULL,
  `numero` INT NULL DEFAULT NULL,
  `cep` VARCHAR(8) NULL DEFAULT NULL,
  `bairro` VARCHAR(50) NULL DEFAULT NULL,
  `cidade` VARCHAR(50) NULL DEFAULT NULL,
  `estado` VARCHAR(2) NULL DEFAULT NULL,
  `complemento` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idendereco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `preco_total_produtos` DECIMAL(7,2) NULL DEFAULT NULL,
  `frete` DECIMAL(7,2) NULL DEFAULT NULL,
  `preco_total_pedido` DECIMAL(7,2) NULL DEFAULT NULL,
  `data_pedido` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idpedido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`pedido_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`pedido_produto` (
  `quantidade` INT NOT NULL,
  `preco_final` DECIMAL(7,2) NULL DEFAULT NULL,
  `valor_total` DECIMAL(7,2) NULL DEFAULT NULL,
  `pedido_idpedido` INT NOT NULL,
  `produto_idproduto` INT NOT NULL,
  PRIMARY KEY (`quantidade`),
  INDEX `fk_pedido_produto_pedido_idx` (`pedido_idpedido` ASC) VISIBLE,
  INDEX `fk_pedido_produto_produto1_idx` (`produto_idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_produto_pedido`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `trabalho_pratico`.`pedido` (`idpedido`),
  CONSTRAINT `fk_pedido_produto_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `trabalho_pratico`.`produto` (`idproduto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `preco_produto` DECIMAL(7,2) NULL DEFAULT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `TrabalhoDelphi`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrabalhoDelphi`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(30) NULL DEFAULT NULL,
  `password` VARCHAR(30) NULL DEFAULT NULL,
  `idDadosPessoais` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_dadospessoais1_idx` (`idDadosPessoais` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_dadospessoais1`
    FOREIGN KEY (`idDadosPessoais`)
    REFERENCES `trabalho_pratico`.`dadospessoais` (`idDadosPessoais`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
