-- MySQL Script generated by MySQL Workbench
-- Fri May 27 12:02:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trabalho_pratico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trabalho_pratico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trabalho_pratico` DEFAULT CHARACTER SET utf8 ;
USE `trabalho_pratico` ;

-- -----------------------------------------------------
-- Table `trabalho_pratico`.`dadosPessoais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_pratico`.`dadosPessoais` (
  `idDadosPessoais` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL,
  `sobrenome` VARCHAR(100) NULL,
  `cpf` VARCHAR(11) NULL,
  `telefone` VARCHAR(11) NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`idDadosPessoais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_pratico`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_pratico`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `descricao` TEXT(255) NULL,
  `preco` DECIMAL(7,2) NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_pratico`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_pratico`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `preco` DECIMAL(7,2) NULL,
  `frete` DECIMAL(7,2) NULL,
  `numeroPedido` INT NULL,
  `idproduto` INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_produto1_idx` (`idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `mydb`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_pratico`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_pratico`.`endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(100) NULL,
  `numero` INT NULL,
  `cep` VARCHAR(8) NULL,
  `bairro` VARCHAR(50) NULL,
  `cidade` VARCHAR(50) NULL,
  `estado` VARCHAR(2) NULL,
  `complemento` TEXT(255) NULL,
  PRIMARY KEY (`idendereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_pratico`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_pratico`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `idDadosPessoais` INT NOT NULL,
  `idpedido` INT NOT NULL,
  `idendereco` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_cliente_dadosPessoais_idx` (`idDadosPessoais` ASC) VISIBLE,
  INDEX `fk_cliente_pedido1_idx` (`idpedido` ASC) VISIBLE,
  INDEX `fk_cliente_endereco1_idx` (`idendereco` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_dadosPessoais`
    FOREIGN KEY (`idDadosPessoais`)
    REFERENCES `mydb`.`dadosPessoais` (`idDadosPessoais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_pedido1`
    FOREIGN KEY (`idpedido`)
    REFERENCES `mydb`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_endereco1`
    FOREIGN KEY (`idendereco`)
    REFERENCES `mydb`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_pratico`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_pratico`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(30) NULL,
  `password` VARCHAR(30) NULL,
  `idcliente` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_cliente1_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
